### ISSUE TITLE
IR-MCI - MTN super low speed or not working . 

### ISSUE THREAD

**Issue by sinaspooler** [RealCuf/VCG-Script#10]
First of all let me thank you for all of your hard work , specially for helping the people of Iran to reach the free Internet . I just tested some of your config , it's ether not working with IR-MCI or it's working with really low speed . I wonder why ?! because reality configs works fine with IR-MCI operator . is it because so many people is using it? or am i doing something wrong !? i tested some of your configs with 1.8.1 xray core and v2rayng and v2rayN desktop .

**Comment by RealCuf** [comment]
### مرسی ممنونم ازت ❤️
----
#### لینک های سابسکرایبشن که در کد قرار داده شده پابلیک هستن و خب ممکنه افراد زیادی در حال استفاده باشن
#### ولی اینو در نظر بگیر که کانفیگ های درون لینک ها همیشه در حال آپدیت هستن
----
> میتونید سورس اسکریپت رو ادیت بزنید و لینک های دلخواه خودتون رو قرار بدید
تا کانفیگ ها نسبت به خصوصیاتی که انتخاب میکنید استخراج بشن
